version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models/pipelines:/app/models/pipelines
    environment:
      - PYTHONUNBUFFERED=1

  db-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: app

    container_name: my-postgres-db
    ports:
      - 5432:5432
    volumes:
      - ./db-volume:/var/lib/postgresql
