services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - ./models/pipelines:/app/models/pipelines
    environment:
      - PYTHONUNBUFFERED=1

  db_talentcare:
    image: postgres:17
    restart: always
    # set shared memory limit when using docker compose
    # or set limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: [REDACTED] # 128*2^20 bytes = 128Mb
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: app
    container_name: db_talentcare
    ports:
      - 8080:5432
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres-project/init-db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
